name: demo-project 

on:
   push:
     branches:
       - main

env:
  GITHUB_TOKEN: ${{ secrets.AWS_GITHUB_TOKEN }}

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build the Docker image
        run: |

            docker build -t 758671678745.dkr.ecr.ap-south-1.amazonaws.com/demo-project:$GITHUB_REF_NAME-$GITHUB_SHA -f Dockerfile